#:schema node_modules/wrangler/config-schema.json
name = "carols"
compatibility_date = "2025-12-02"
pages_build_output_dir = "./public"

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
